# Feature Selection

We select from a ranked list of features resulting from the algorithm developed in [DMEPOS_Feature_Ranking.ipynb](./DMEPOS_Feature_Ranking.ipynb) using ANOVA on 5-fold-by-provider cross validation area under the precision-recall curve (AUPRC) scores to determine the minimum number of useful features at least as good as a model built with all features as suggested by Hancock, J. T., Bauder, R. A., Wang, H., & Khoshgoftaar, T. M. (2023).

## WARNING! The following file must be run before using this script.
* SpIn_2_Artifacts/dmepos_amount_stats_labeled_silver.ipynb

In [1]:
import sys
print(sys.executable)

/cluster/software/conda-envs-global/jupyter/envs/jupytern_706/bin/python

In [2]:
%pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /home/ckgnr/.local/lib/python3.11/site-packages (from scikit-learn) (2.4.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 3.0 MB/s eta 0:00:00
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 59.3 MB/s eta 0:00:0000:0100:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.1/309.1 kB 43.9 MB/s eta 0:00:00
Downloading scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 63.6 MB/s eta 0:00:00a 0:00:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install catboost

Defaulting to user installation because normal site-packages is not writeable
Collecting catboost
  Downloading catboost-1.2.10-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Collecting matplotlib (from catboost)
  Downloading matplotlib-3.10.8-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: numpy<3.0,>=1.16.0 in /home/ckgnr/.local/lib/python3.11/site-packages (from catboost) (2.4.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /home/ckgnr/.local/lib/python3.11/site-packages (from catboost) (3.0.0)
Requirement already satisfied: scipy in /home/ckgnr/.local/lib/python3.11/site-packages (from catboost) (1.17.1)
Collecting plotly (from catboost)
  Downloading plotly-6.5.2-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: six in /cluster/software/conda-envs-global/jupyter/envs/jupytern_706/lib/python3.11/site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /cluster/software/conda-envs-global/jupyter/envs/jupytern_706/lib/python3.11/site-packages (from pandas<4.0,>=0.24->catboost) (2.8.2)
Collecting contourpy>=1.0.1 (from matplotlib->catboost)
  Downloading contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->catboost)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->catboost)
  Downloading fonttools-4.61.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 6.8 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib->catboost)
  Downloading kiwisolver-1.4.9-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in /cluster/software/conda-envs-global/jupyter/envs/jupytern_706/lib/python3.11/site-packages (from matplotlib->catboost) (23.1)
Collecting pillow>=8 (from matplotlib->catboost)
  Downloading pillow-12.1.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib->catboost)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Downloading narwhals-2.17.0-py3-none-any.whl.metadata (14 kB)
Downloading catboost-1.2.10-cp311-cp311-manylinux2014_x86_64.whl (97.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.2/97.2 MB 43.4 MB/s eta 0:00:0000:0100:01
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 6.4 MB/s eta 0:00:00
Downloading matplotlib-3.10.8-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 54.1 MB/s eta 0:00:00a 0:00:01
Downloading plotly-6.5.2-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 54.0 MB/s eta 0:00:0000:0100:01
Downloading contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (355 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 355.2/355.2 kB 19.6 MB/s eta 0:00:00
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 51.5 MB/s eta 0:00:00a 0:00:01
Downloading kiwisolver-1.4.9-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 54.7 MB/s eta 0:00:00
Downloading narwhals-2.17.0-py3-none-any.whl (444 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.9/444.9 kB 24.6 MB/s eta 0:00:00
Downloading pillow-12.1.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 53.3 MB/s eta 0:00:00a 0:00:01
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.8/122.8 kB 7.8 MB/s eta 0:00:00
Installing collected packages: pyparsing, pillow, narwhals, kiwisolver, graphviz, fonttools, cycler, contourpy, plotly, matplotlib, catboost
Successfully installed catboost-1.2.10 contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 graphviz-0.21 kiwisolver-1.4.9 matplotlib-3.10.8 narwhals-2.17.0 pillow-12.1.1 plotly-6.5.2 pyparsing-3.3.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /home/ckgnr/.local/lib/python3.11/site-packages (from xgboost) (2.4.2)
Collecting nvidia-nccl-cu12 (from xgboost)
  Downloading nvidia_nccl_cu12-2.29.3-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: scipy in /home/ckgnr/.local/lib/python3.11/site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-manylinux_2_28_x86_64.whl (131.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.7/131.7 MB 39.0 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nccl_cu12-2.29.3-py3-none-manylinux_2_18_x86_64.whl (289.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.8/289.8 MB 30.4 MB/s eta 0:00:0000:0100:01
Installing collected packages: nvidia-nccl-cu12, xgboost
Successfully installed nvidia-nccl-cu12-2.29.3 xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in /home/ckgnr/.local/lib/python3.11/site-packages (from lightgbm) (2.4.2)
Requirement already satisfied: scipy in /home/ckgnr/.local/lib/python3.11/site-packages (from lightgbm) (1.17.1)
Downloading lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 24.9 MB/s eta 0:00:0000:0100:01
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0
Note: you may need to restart the kernel to use updated packages.

## Load modules

In [1]:
import pandas as pd
import numpy as np
import re
from catboost import CatBoostClassifier, Pool
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
import lightgbm as lgb
from sklearn.tree import DecisionTreeClassifier

## Load and transform data

In [4]:
df = pd.read_csv('/cluster/pixstor/haithcoatt-lab/SP26cCapStone_Team2/Data/Silver/dmepos_amount_stats_labeled.csv') # load

df.head()

,npi,rfrg_prvdr_state_abrvtn,year,target,avg_suplr_sbmtd_chrg_mean,avg_suplr_mdcr_alowd_amt_mean,avg_suplr_mdcr_pymt_amt_mean,avg_suplr_mdcr_stdzd_amt_mean,avg_suplr_sbmtd_chrg_sum,avg_suplr_mdcr_alowd_amt_sum,...,rfrg_prvdr_spclty_desc_student_in_an_organized_health_care_education_training_program,rfrg_prvdr_spclty_desc_surgery,rfrg_prvdr_spclty_desc_surgical_oncology,rfrg_prvdr_spclty_desc_thoracic_surgery,rfrg_prvdr_spclty_desc_thoracic_surgery_cardiothoracic_vascular_surgery,rfrg_prvdr_spclty_desc_undefined_physician_type,rfrg_prvdr_spclty_desc_undersea_and_hyperbaric_medicine,rfrg_prvdr_spclty_desc_unknown_supplier_provider_specialty,rfrg_prvdr_spclty_desc_urology,rfrg_prvdr_spclty_desc_vascular_surgery
0,1003000597,OK,2022,0,6.155416,2.196826,1.692306,1.702371,6.155416,2.196826,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1003000597,OK,2023,0,12.431501,6.574868,4.766645,5.263697,62.157505,32.874340,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1003000902,KY,2021,0,97.751851,26.709274,19.463974,18.978969,782.014805,213.674191,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1003000902,KY,2022,0,80.839496,18.260912,13.472218,12.561403,404.197480,91.304560,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1003000902,KY,2023,0,39.630693,14.071564,10.200556,10.291238,158.522774,56.286255,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
X_train = df.drop(columns=['npi','rfrg_prvdr_state_abrvtn','year','target']).fillna(0) # the NaNs derive from insufficient data to compute std devs for some provider features
groups = df.npi # store npi in groups to ensure the same individual cannot be in both training and validation during cv
y_train = df.target
feature_names = X_train.columns.tolist()

## Feature Ranking algorithm

In [6]:
def get_rankings(X_train, y_train, classifier_array):
    """Returns a dataframe of the rank of each feature (row) in the ranking supplied
    by the given classifier algorithm(s) (column)."""
    df_rankings = pd.DataFrame(index=X_train.columns)
    # NOTE: if using XGB then StandardScaler must be applied
    for model, name in zip(classifier_array, labels):
        # addn'l preprocessing for XGB only
        if name == 'XGBClassifier':
            # apply standard scaler
            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            # and train on the scaled data
            model.fit(X_train_scaled, y_train)
        else:
            # perform the usual training
            model.fit(X_train, y_train)

        # form a series of feature importance values indexed by feature_names
        feature_import_series = pd.Series(model.feature_importances_, index=feature_names).sort_values(ascending=False)
        # convert into a ranking and insert into the dataframe
        df_rankings[name] = feature_import_series.index.get_indexer(X_train.columns)

    # calculate the median ranks for each feature and sort ascending
    df_rankings['median_rank'] = df_rankings.apply(np.median, axis=1)
    df_rankings.sort_values(by='median_rank', inplace=True)
    return df_rankings

#### This takes a significant amount of time to run.

In [7]:
# init the base learners
catboost = CatBoostClassifier(iterations=100, verbose=0) # parameters given by Google Search AI Overview
xgb = XGBClassifier()
rf = RandomForestClassifier(random_state=8090)
et = ExtraTreesClassifier(n_estimators=100, random_state=8090)
lgbm = lgb.LGBMClassifier(random_state=8090)
dt = DecisionTreeClassifier(random_state=8090)

# gather them
classifier_array = [catboost, xgb, rf, et, lgbm, dt]
labels = [clf.__class__.__name__ for clf in classifier_array]

# run the ranking algorithm
df_rankings = get_rankings(X_train, y_train, classifier_array)
df_rankings.head()

[LightGBM] [Info] Number of positive: 44, number of negative: 140783
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.094873 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 20527
[LightGBM] [Info] Number of data points in the train set: 140827, number of used features: 155
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000312 -> initscore=-8.070785
[LightGBM] [Info] Start training from score -8.070785

,CatBoostClassifier,XGBClassifier,RandomForestClassifier,ExtraTreesClassifier,LGBMClassifier,DecisionTreeClassifier,median_rank
avg_suplr_sbmtd_chrg_sum,37,48,0,1,2,1,1.5
avg_suplr_sbmtd_chrg_max,23,47,3,8,7,2,7.5
avg_suplr_mdcr_stdzd_amt_sum,11,18,9,3,14,0,10.0
avg_suplr_sbmtd_chrg_mean,15,60,1,4,6,14,10.0
avg_suplr_mdcr_pymt_amt_sum,8,12,12,9,36,56,12.0

In [8]:
df_rankings.to_pickle('feature_rankings.pkl')

## Feature Selection

In [4]:
# get the ranking df
df_rankings = pd.read_pickle('feature_rankings.pkl')
df_rankings.head()

,CatBoostClassifier,XGBClassifier,RandomForestClassifier,ExtraTreesClassifier,LGBMClassifier,DecisionTreeClassifier,median_rank
avg_suplr_sbmtd_chrg_median,1,66,8,5,22,2,6.5
bene_avg_age,12,61,16,4,0,1,8.0
avg_suplr_sbmtd_chrg_min,10,64,12,1,1,50,11.0
avg_suplr_mdcr_stdzd_amt_min,34,28,6,7,19,7,13.0
avg_suplr_sbmtd_chrg_mean,45,27,4,13,14,0,13.5

In [5]:
# unique median_rank
median_ranks = df_rankings.median_rank.unique()
median_ranks

array([  6.5,   8. ,  11. ,  13. ,  13.5,  16.5,  19.5,  20. ,  20.5,
        21. ,  22.5,  23.5,  24. ,  25. ,  25.5,  26. ,  26.5,  27.5,
        29. ,  29.5,  30. ,  30.5,  32. ,  33. ,  33.5,  34. ,  36. ,
        36.5,  37.5,  40. ,  41. ,  41.5,  42. ,  42.5,  43.5,  44.5,
        45.5,  46. ,  46.5,  49. ,  49.5,  50. ,  52.5,  56. ,  57. ,
        57.5,  60.5,  61. ,  61.5,  62. ,  62.5,  65.5,  67. ,  68. ,
        68.5,  70.5,  71.5,  75. ,  76. ,  80. ,  81.5,  82.5,  83.5,
        84. ,  85. ,  87.5,  88.5,  90. ,  92.5,  93.5,  94. ,  95.5,
        98.5,  99.5, 100. , 105.5, 106.5, 110. , 111. , 111.5, 112. ,
       113. , 114. , 114.5, 116.5, 117. , 118. , 119.5, 120.5, 121. ,
       121.5, 123. , 123.5, 124.5, 125. , 126. , 127. , 128.5, 129. ,
       129.5, 130. , 131. , 132. , 132.5, 133. , 134. , 134.5, 135. ,
       137. , 137.5, 138.5, 139. , 139.5, 141. , 141.5, 142. , 144. ,
       151. , 152. , 153. , 153.5, 154. , 158.5, 161. , 162. , 163.5,
       164.5, 165. , 166. , 169. , 169.5, 170. , 170.5, 171. , 172. ,
       173.5, 174. , 175. , 177.5, 179. , 180. , 184. , 184.5, 185. ,
       185.5, 187. , 190. , 190.5, 191. , 193.5, 194. , 194.5, 196. ,
       197. , 198. , 199. , 200. , 202. , 204. , 205. , 206. , 206.5,
       207. , 208. , 209.5, 210. , 211. , 212. , 213.5, 214. , 215.5,
       217. ])

In [6]:
# number of unique median_rank
df_rankings.median_rank.nunique()

172

In [7]:
# double check
len(median_ranks)

172

## Prototyping the selection algorithm

In [8]:
# necessary modules
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import precision_recall_curve, auc, average_precision_score

### CatBoost

In [11]:
sgkf = StratifiedGroupKFold(n_splits=5)

auprc_scores = []

# get feature set from df_ranking and filter X_train
feats = df_rankings[df_rankings.median_rank <= 6.5].index
X = X_train.filter(items=feats, axis='columns')

# the model
model = CatBoostClassifier(iterations=100, eval_metric='PRAUC', verbose=0)

for train_idx, val_idx in sgkf.split(X, y_train, groups):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    # train and fit the model
    model.fit(X_tr, y_tr, eval_set=(X_val, y_val))
    
    # Calculate AUPRC on validation set
    preds = model.predict_proba(X_val)[:, 1]
    precision, recall, _ = precision_recall_curve(y_val, preds)
    auprc = auc(recall, precision)
    auprc_scores.append(auprc)

# need to store results w/ a column for classifier, num_features, auprc
cv_res = {'classifier' : [model.__class__.__name__]*5,
          'num_features' : [len(feats)]*5,
          'auprc' : auprc_scores}

df_cv_res = pd.DataFrame(data=cv_res)
df_cv_res

           classifier  num_features     auprc
0  CatBoostClassifier             1  0.045996
1  CatBoostClassifier             1  0.000575
2  CatBoostClassifier             1  0.000540
3  CatBoostClassifier             1  0.000442
4  CatBoostClassifier             1  0.000558

### XGBoost

In [19]:
sgkf = StratifiedGroupKFold(n_splits=5)

auprc_scores = []

# get feature set from df_ranking and filter X_train
feats = df_rankings[df_rankings.median_rank <= 6.5].index

model = XGBClassifier(eval_metric='aucpr')
X = X_train.filter(items=feats, axis='columns')

for train_idx, val_idx in sgkf.split(X, y_train, groups):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    # train and fit the model
    model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)]) # eval_set needs to be a list for XGBoost
    
    # Calculate AUPRC on validation set
    preds = model.predict_proba(X_val)[:, 1]
    
    auprc = average_precision_score(y_val, preds)
    auprc_scores.append(auprc)

# need to store results w/ a column for classifier, num_features, auprc
cv_res = {'classifier' : [ model.__class__.__name__]*5,
          'num_features' : [len(feats)]*5,
          'auprc' : auprc_scores}

df_cv_res = pd.DataFrame(data=cv_res)
df_cv_res

[0]	validation_0-aucpr:0.00046
[1]	validation_0-aucpr:0.00042
[2]	validation_0-aucpr:0.00037
[3]	validation_0-aucpr:0.00036
[4]	validation_0-aucpr:0.00033
[5]	validation_0-aucpr:0.00033
[6]	validation_0-aucpr:0.00033
[7]	validation_0-aucpr:0.00030
[8]	validation_0-aucpr:0.00029
[9]	validation_0-aucpr:0.00031
[10]	validation_0-aucpr:0.00031
[11]	validation_0-aucpr:0.00029
[12]	validation_0-aucpr:0.00029
[13]	validation_0-aucpr:0.00029
[14]	validation_0-aucpr:0.00029
[15]	validation_0-aucpr:0.00029
[16]	validation_0-aucpr:0.00028
[17]	validation_0-aucpr:0.00028
[18]	validation_0-aucpr:0.00028
[19]	validation_0-aucpr:0.00028
[20]	validation_0-aucpr:0.00029
[21]	validation_0-aucpr:0.00028
[22]	validation_0-aucpr:0.00028
[23]	validation_0-aucpr:0.00028
[24]	validation_0-aucpr:0.00028
[25]	validation_0-aucpr:0.00029
[26]	validation_0-aucpr:0.00028
[27]	validation_0-aucpr:0.00028
[28]	validation_0-aucpr:0.00028
[29]	validation_0-aucpr:0.00028
[30]	validation_0-aucpr:0.00028
[31]	validation_0-aucpr:0.00028
[32]	validation_0-aucpr:0.00028
[33]	validation_0-aucpr:0.00028
[34]	validation_0-aucpr:0.00028
[35]	validation_0-aucpr:0.00028
[36]	validation_0-aucpr:0.00028
[37]	validation_0-aucpr:0.00028
[38]	validation_0-aucpr:0.00028
[39]	validation_0-aucpr:0.00028
[40]	validation_0-aucpr:0.00028
[41]	validation_0-aucpr:0.00028
[42]	validation_0-aucpr:0.00028
[43]	validation_0-aucpr:0.00028
[44]	validation_0-aucpr:0.00028
[45]	validation_0-aucpr:0.00028
[46]	validation_0-aucpr:0.00028
[47]	validation_0-aucpr:0.00028
[48]	validation_0-aucpr:0.00028
[49]	validation_0-aucpr:0.00028
[50]	validation_0-aucpr:0.00028
[51]	validation_0-aucpr:0.00028
[52]	validation_0-aucpr:0.00028
[53]	validation_0-aucpr:0.00029
[54]	validation_0-aucpr:0.00028
[55]	validation_0-aucpr:0.00028
[56]	validation_0-aucpr:0.00028
[57]	validation_0-aucpr:0.00028
[58]	validation_0-aucpr:0.00028
[59]	validation_0-aucpr:0.00028
[60]	validation_0-aucpr:0.00029
[61]	validation_0-aucpr:0.00028
[62]	validation_0-aucpr:0.00029
[63]	validation_0-aucpr:0.00029
[64]	validation_0-aucpr:0.00029
[65]	validation_0-aucpr:0.00029
[66]	validation_0-aucpr:0.00029
[67]	validation_0-aucpr:0.00029
[68]	validation_0-aucpr:0.00029
[69]	validation_0-aucpr:0.00029
[70]	validation_0-aucpr:0.00029
[71]	validation_0-aucpr:0.00029
[72]	validation_0-aucpr:0.00029
[73]	validation_0-aucpr:0.00029
[74]	validation_0-aucpr:0.00029
[75]	validation_0-aucpr:0.00029
[76]	validation_0-aucpr:0.00029
[77]	validation_0-aucpr:0.00029
[78]	validation_0-aucpr:0.00029
[79]	validation_0-aucpr:0.00029
[80]	validation_0-aucpr:0.00029
[81]	validation_0-aucpr:0.00029
[82]	validation_0-aucpr:0.00029
[83]	validation_0-aucpr:0.00029
[84]	validation_0-aucpr:0.00029
[85]	validation_0-aucpr:0.00029
[86]	validation_0-aucpr:0.00029
[87]	validation_0-aucpr:0.00029
[88]	validation_0-aucpr:0.00029
[89]	validation_0-aucpr:0.00030
[90]	validation_0-aucpr:0.00029
[91]	validation_0-aucpr:0.00029
[92]	validation_0-aucpr:0.00029
[93]	validation_0-aucpr:0.00029
[94]	validation_0-aucpr:0.00029
[95]	validation_0-aucpr:0.00029
[96]	validation_0-aucpr:0.00029
[97]	validation_0-aucpr:0.00029
[98]	validation_0-aucpr:0.00029
[99]	validation_0-aucpr:0.00029
[0]	validation_0-aucpr:0.00037
[1]	validation_0-aucpr:0.00040
[2]	validation_0-aucpr:0.00044
[3]	validation_0-aucpr:0.00055
[4]	validation_0-aucpr:0.00052
[5]	validation_0-aucpr:0.00053
[6]	validation_0-aucpr:0.00055
[7]	validation_0-aucpr:0.00057
[8]	validation_0-aucpr:0.00044
[9]	validation_0-aucpr:0.00042
[10]	validation_0-aucpr:0.00042
[11]	validation_0-aucpr:0.00041
[12]	validation_0-aucpr:0.00040
[13]	validation_0-aucpr:0.00040
[14]	validation_0-aucpr:0.00038
[15]	validation_0-aucpr:0.00039
[16]	validation_0-aucpr:0.00038
[17]	validation_0-aucpr:0.00038
[18]	validation_0-aucpr:0.00039
[19]	validation_0-aucpr:0.00037
[20]	validation_0-aucpr:0.00038
[21]	validation_0-aucpr:0.00040
[22]	validation_0-aucpr:0.00036
[23]	validation_0-aucpr:0.00036
[24]	validation_0-aucpr:0.00036
[25]	validation_0-aucpr:0.00036
[26]	validation_0-aucpr:0.00034
[27]	validation_0-aucpr:0.00035
[28]	validation_0-aucpr:0.00033
[29]	validation_0-aucpr:0.00032
[30]	validation_0-aucpr:0.00033
[31]	validation_0-aucpr:0.00033
[32]	validation_0-aucpr:0.00034
[33]	validation_0-aucpr:0.00034
[34]	validation_0-aucpr:0.00033
[35]	validation_0-aucpr:0.00033
[36]	validation_0-aucpr:0.00033
[37]	validation_0-aucpr:0.00033
[38]	validation_0-aucpr:0.00033
[39]	validation_0-aucpr:0.00032
[40]	validation_0-aucpr:0.00033
[41]	validation_0-aucpr:0.00032
[42]	validation_0-aucpr:0.00032
[43]	validation_0-aucpr:0.00032
[44]	validation_0-aucpr:0.00032
[45]	validation_0-aucpr:0.00031
[46]	validation_0-aucpr:0.00032
[47]	validation_0-aucpr:0.00031
[48]	validation_0-aucpr:0.00031
[49]	validation_0-aucpr:0.00031
[50]	validation_0-aucpr:0.00031
[51]	validation_0-aucpr:0.00031
[52]	validation_0-aucpr:0.00031
[53]	validation_0-aucpr:0.00031
[54]	validation_0-aucpr:0.00031
[55]	validation_0-aucpr:0.00031
[56]	validation_0-aucpr:0.00031
[57]	validation_0-aucpr:0.00031
[58]	validation_0-aucpr:0.00030
[59]	validation_0-aucpr:0.00030
[60]	validation_0-aucpr:0.00031
[61]	validation_0-aucpr:0.00031
[62]	validation_0-aucpr:0.00031
[63]	validation_0-aucpr:0.00031
[64]	validation_0-aucpr:0.00031
[65]	validation_0-aucpr:0.00031
[66]	validation_0-aucpr:0.00031
[67]	validation_0-aucpr:0.00031
[68]	validation_0-aucpr:0.00031
[69]	validation_0-aucpr:0.00031
[70]	validation_0-aucpr:0.00031
[71]	validation_0-aucpr:0.00031
[72]	validation_0-aucpr:0.00031
[73]	validation_0-aucpr:0.00031
[74]	validation_0-aucpr:0.00031
[75]	validation_0-aucpr:0.00031
[76]	validation_0-aucpr:0.00031
[77]	validation_0-aucpr:0.00031
[78]	validation_0-aucpr:0.00031
[79]	validation_0-aucpr:0.00031
[80]	validation_0-aucpr:0.00031
[81]	validation_0-aucpr:0.00031
[82]	validation_0-aucpr:0.00031
[83]	validation_0-aucpr:0.00031
[84]	validation_0-aucpr:0.00030
[85]	validation_0-aucpr:0.00031
[86]	validation_0-aucpr:0.00031
[87]	validation_0-aucpr:0.00031
[88]	validation_0-aucpr:0.00031
[89]	validation_0-aucpr:0.00031
[90]	validation_0-aucpr:0.00031
[91]	validation_0-aucpr:0.00031
[92]	validation_0-aucpr:0.00031
[93]	validation_0-aucpr:0.00031
[94]	validation_0-aucpr:0.00031
[95]	validation_0-aucpr:0.00031
[96]	validation_0-aucpr:0.00031
[97]	validation_0-aucpr:0.00031
[98]	validation_0-aucpr:0.00031
[99]	validation_0-aucpr:0.00031
[0]	validation_0-aucpr:0.00032
[1]	validation_0-aucpr:0.00027
[2]	validation_0-aucpr:0.00028
[3]	validation_0-aucpr:0.00028
[4]	validation_0-aucpr:0.00029
[5]	validation_0-aucpr:0.00029
[6]	validation_0-aucpr:0.00029
[7]	validation_0-aucpr:0.00032
[8]	validation_0-aucpr:0.00033
[9]	validation_0-aucpr:0.00035
[10]	validation_0-aucpr:0.00037
[11]	validation_0-aucpr:0.00036
[12]	validation_0-aucpr:0.00037
[13]	validation_0-aucpr:0.00038
[14]	validation_0-aucpr:0.00034
[15]	validation_0-aucpr:0.00033
[16]	validation_0-aucpr:0.00035
[17]	validation_0-aucpr:0.00036
[18]	validation_0-aucpr:0.00037
[19]	validation_0-aucpr:0.00037
[20]	validation_0-aucpr:0.00037
[21]	validation_0-aucpr:0.00036
[22]	validation_0-aucpr:0.00037
[23]	validation_0-aucpr:0.00036
[24]	validation_0-aucpr:0.00035
[25]	validation_0-aucpr:0.00035
[26]	validation_0-aucpr:0.00034
[27]	validation_0-aucpr:0.00036
[28]	validation_0-aucpr:0.00037
[29]	validation_0-aucpr:0.00036
[30]	validation_0-aucpr:0.00036
[31]	validation_0-aucpr:0.00037
[32]	validation_0-aucpr:0.00037
[33]	validation_0-aucpr:0.00039
[34]	validation_0-aucpr:0.00039
[35]	validation_0-aucpr:0.00040
[36]	validation_0-aucpr:0.00040
[37]	validation_0-aucpr:0.00038
[38]	validation_0-aucpr:0.00037
[39]	validation_0-aucpr:0.00037
[40]	validation_0-aucpr:0.00038
[41]	validation_0-aucpr:0.00038
[42]	validation_0-aucpr:0.00038
[43]	validation_0-aucpr:0.00038
[44]	validation_0-aucpr:0.00039
[45]	validation_0-aucpr:0.00039
[46]	validation_0-aucpr:0.00039
[47]	validation_0-aucpr:0.00039
[48]	validation_0-aucpr:0.00040
[49]	validation_0-aucpr:0.00037
[50]	validation_0-aucpr:0.00037
[51]	validation_0-aucpr:0.00038
[52]	validation_0-aucpr:0.00038
[53]	validation_0-aucpr:0.00038
[54]	validation_0-aucpr:0.00038
[55]	validation_0-aucpr:0.00038
[56]	validation_0-aucpr:0.00038
[57]	validation_0-aucpr:0.00038
[58]	validation_0-aucpr:0.00038
[59]	validation_0-aucpr:0.00039
[60]	validation_0-aucpr:0.00039
[61]	validation_0-aucpr:0.00039
[62]	validation_0-aucpr:0.00040
[63]	validation_0-aucpr:0.00039
[64]	validation_0-aucpr:0.00040
[65]	validation_0-aucpr:0.00040
[66]	validation_0-aucpr:0.00040
[67]	validation_0-aucpr:0.00040
[68]	validation_0-aucpr:0.00040
[69]	validation_0-aucpr:0.00040
[70]	validation_0-aucpr:0.00040
[71]	validation_0-aucpr:0.00041
[72]	validation_0-aucpr:0.00041
[73]	validation_0-aucpr:0.00041
[74]	validation_0-aucpr:0.00042
[75]	validation_0-aucpr:0.00043
[76]	validation_0-aucpr:0.00042
[77]	validation_0-aucpr:0.00042
[78]	validation_0-aucpr:0.00041
[79]	validation_0-aucpr:0.00040
[80]	validation_0-aucpr:0.00041
[81]	validation_0-aucpr:0.00041
[82]	validation_0-aucpr:0.00042
[83]	validation_0-aucpr:0.00041
[84]	validation_0-aucpr:0.00042
[85]	validation_0-aucpr:0.00042
[86]	validation_0-aucpr:0.00042
[87]	validation_0-aucpr:0.00042
[88]	validation_0-aucpr:0.00041
[89]	validation_0-aucpr:0.00041
[90]	validation_0-aucpr:0.00042
[91]	validation_0-aucpr:0.00043
[92]	validation_0-aucpr:0.00043
[93]	validation_0-aucpr:0.00042
[94]	validation_0-aucpr:0.00042
[95]	validation_0-aucpr:0.00042
[96]	validation_0-aucpr:0.00043
[97]	validation_0-aucpr:0.00043
[98]	validation_0-aucpr:0.00044
[99]	validation_0-aucpr:0.00044
[0]	validation_0-aucpr:0.00029
[1]	validation_0-aucpr:0.00030
[2]	validation_0-aucpr:0.00029
[3]	validation_0-aucpr:0.00029
[4]	validation_0-aucpr:0.00028
[5]	validation_0-aucpr:0.00028
[6]	validation_0-aucpr:0.00029
[7]	validation_0-aucpr:0.00031
[8]	validation_0-aucpr:0.00030
[9]	validation_0-aucpr:0.00033
[10]	validation_0-aucpr:0.00031
[11]	validation_0-aucpr:0.00031
[12]	validation_0-aucpr:0.00031
[13]	validation_0-aucpr:0.00031
[14]	validation_0-aucpr:0.00030
[15]	validation_0-aucpr:0.00030
[16]	validation_0-aucpr:0.00031
[17]	validation_0-aucpr:0.00032
[18]	validation_0-aucpr:0.00032
[19]	validation_0-aucpr:0.00031
[20]	validation_0-aucpr:0.00033
[21]	validation_0-aucpr:0.00034
[22]	validation_0-aucpr:0.00033
[23]	validation_0-aucpr:0.00033
[24]	validation_0-aucpr:0.00032
[25]	validation_0-aucpr:0.00032
[26]	validation_0-aucpr:0.00032
[27]	validation_0-aucpr:0.00033
[28]	validation_0-aucpr:0.00032
[29]	validation_0-aucpr:0.00033
[30]	validation_0-aucpr:0.00033
[31]	validation_0-aucpr:0.00032
[32]	validation_0-aucpr:0.00032
[33]	validation_0-aucpr:0.00032
[34]	validation_0-aucpr:0.00032
[35]	validation_0-aucpr:0.00031
[36]	validation_0-aucpr:0.00031
[37]	validation_0-aucpr:0.00032
[38]	validation_0-aucpr:0.00032
[39]	validation_0-aucpr:0.00032
[40]	validation_0-aucpr:0.00032
[41]	validation_0-aucpr:0.00032
[42]	validation_0-aucpr:0.00032
[43]	validation_0-aucpr:0.00032
[44]	validation_0-aucpr:0.00032
[45]	validation_0-aucpr:0.00032
[46]	validation_0-aucpr:0.00031
[47]	validation_0-aucpr:0.00032
[48]	validation_0-aucpr:0.00032
[49]	validation_0-aucpr:0.00032
[50]	validation_0-aucpr:0.00032
[51]	validation_0-aucpr:0.00031
[52]	validation_0-aucpr:0.00032
[53]	validation_0-aucpr:0.00031
[54]	validation_0-aucpr:0.00032
[55]	validation_0-aucpr:0.00032
[56]	validation_0-aucpr:0.00032
[57]	validation_0-aucpr:0.00032
[58]	validation_0-aucpr:0.00032
[59]	validation_0-aucpr:0.00031
[60]	validation_0-aucpr:0.00031
[61]	validation_0-aucpr:0.00031
[62]	validation_0-aucpr:0.00032
[63]	validation_0-aucpr:0.00031
[64]	validation_0-aucpr:0.00031
[65]	validation_0-aucpr:0.00031
[66]	validation_0-aucpr:0.00031
[67]	validation_0-aucpr:0.00031
[68]	validation_0-aucpr:0.00030
[69]	validation_0-aucpr:0.00031
[70]	validation_0-aucpr:0.00030
[71]	validation_0-aucpr:0.00031
[72]	validation_0-aucpr:0.00031
[73]	validation_0-aucpr:0.00031
[74]	validation_0-aucpr:0.00031
[75]	validation_0-aucpr:0.00031
[76]	validation_0-aucpr:0.00031
[77]	validation_0-aucpr:0.00031
[78]	validation_0-aucpr:0.00031
[79]	validation_0-aucpr:0.00031
[80]	validation_0-aucpr:0.00030
[81]	validation_0-aucpr:0.00031
[82]	validation_0-aucpr:0.00031
[83]	validation_0-aucpr:0.00031
[84]	validation_0-aucpr:0.00031
[85]	validation_0-aucpr:0.00030
[86]	validation_0-aucpr:0.00031
[87]	validation_0-aucpr:0.00030
[88]	validation_0-aucpr:0.00031
[89]	validation_0-aucpr:0.00031
[90]	validation_0-aucpr:0.00031
[91]	validation_0-aucpr:0.00031
[92]	validation_0-aucpr:0.00031
[93]	validation_0-aucpr:0.00031
[94]	validation_0-aucpr:0.00031
[95]	validation_0-aucpr:0.00031
[96]	validation_0-aucpr:0.00031
[97]	validation_0-aucpr:0.00031
[98]	validation_0-aucpr:0.00031
[99]	validation_0-aucpr:0.00030
[0]	validation_0-aucpr:0.00027
[1]	validation_0-aucpr:0.00028
[2]	validation_0-aucpr:0.00029
[3]	validation_0-aucpr:0.00029
[4]	validation_0-aucpr:0.00029
[5]	validation_0-aucpr:0.00028
[6]	validation_0-aucpr:0.00028
[7]	validation_0-aucpr:0.00029
[8]	validation_0-aucpr:0.00029
[9]	validation_0-aucpr:0.00029
[10]	validation_0-aucpr:0.00030
[11]	validation_0-aucpr:0.00030
[12]	validation_0-aucpr:0.00030
[13]	validation_0-aucpr:0.00029
[14]	validation_0-aucpr:0.00029
[15]	validation_0-aucpr:0.00028
[16]	validation_0-aucpr:0.00030
[17]	validation_0-aucpr:0.00030
[18]	validation_0-aucpr:0.00031
[19]	validation_0-aucpr:0.00031
[20]	validation_0-aucpr:0.00031
[21]	validation_0-aucpr:0.00032
[22]	validation_0-aucpr:0.00031
[23]	validation_0-aucpr:0.00029
[24]	validation_0-aucpr:0.00030
[25]	validation_0-aucpr:0.00034
[26]	validation_0-aucpr:0.00032
[27]	validation_0-aucpr:0.00030
[28]	validation_0-aucpr:0.00030
[29]	validation_0-aucpr:0.00031
[30]	validation_0-aucpr:0.00031
[31]	validation_0-aucpr:0.00031
[32]	validation_0-aucpr:0.00032
[33]	validation_0-aucpr:0.00032
[34]	validation_0-aucpr:0.00030
[35]	validation_0-aucpr:0.00030
[36]	validation_0-aucpr:0.00030
[37]	validation_0-aucpr:0.00030
[38]	validation_0-aucpr:0.00030
[39]	validation_0-aucpr:0.00032
[40]	validation_0-aucpr:0.00032
[41]	validation_0-aucpr:0.00032
[42]	validation_0-aucpr:0.00032
[43]	validation_0-aucpr:0.00031
[44]	validation_0-aucpr:0.00031
[45]	validation_0-aucpr:0.00031
[46]	validation_0-aucpr:0.00032
[47]	validation_0-aucpr:0.00032
[48]	validation_0-aucpr:0.00032
[49]	validation_0-aucpr:0.00032
[50]	validation_0-aucpr:0.00032
[51]	validation_0-aucpr:0.00032
[52]	validation_0-aucpr:0.00032
[53]	validation_0-aucpr:0.00033
[54]	validation_0-aucpr:0.00033
[55]	validation_0-aucpr:0.00034
[56]	validation_0-aucpr:0.00034
[57]	validation_0-aucpr:0.00034
[58]	validation_0-aucpr:0.00034
[59]	validation_0-aucpr:0.00034
[60]	validation_0-aucpr:0.00034
[61]	validation_0-aucpr:0.00035
[62]	validation_0-aucpr:0.00034
[63]	validation_0-aucpr:0.00035
[64]	validation_0-aucpr:0.00033
[65]	validation_0-aucpr:0.00035
[66]	validation_0-aucpr:0.00035
[67]	validation_0-aucpr:0.00035
[68]	validation_0-aucpr:0.00035
[69]	validation_0-aucpr:0.00034
[70]	validation_0-aucpr:0.00035
[71]	validation_0-aucpr:0.00035
[72]	validation_0-aucpr:0.00035
[73]	validation_0-aucpr:0.00036
[74]	validation_0-aucpr:0.00036
[75]	validation_0-aucpr:0.00036
[76]	validation_0-aucpr:0.00035
[77]	validation_0-aucpr:0.00036
[78]	validation_0-aucpr:0.00036
[79]	validation_0-aucpr:0.00036
[80]	validation_0-aucpr:0.00036
[81]	validation_0-aucpr:0.00036
[82]	validation_0-aucpr:0.00036
[83]	validation_0-aucpr:0.00036
[84]	validation_0-aucpr:0.00036
[85]	validation_0-aucpr:0.00036
[86]	validation_0-aucpr:0.00036
[87]	validation_0-aucpr:0.00036
[88]	validation_0-aucpr:0.00036
[89]	validation_0-aucpr:0.00036
[90]	validation_0-aucpr:0.00036
[91]	validation_0-aucpr:0.00035
[92]	validation_0-aucpr:0.00034
[93]	validation_0-aucpr:0.00034
[94]	validation_0-aucpr:0.00036
[95]	validation_0-aucpr:0.00036
[96]	validation_0-aucpr:0.00036
[97]	validation_0-aucpr:0.00036
[98]	validation_0-aucpr:0.00036
[99]	validation_0-aucpr:0.00036

      classifier  num_features     auprc
0  XGBClassifier             1  0.000327
1  XGBClassifier             1  0.000365
2  XGBClassifier             1  0.000519
3  XGBClassifier             1  0.000366
4  XGBClassifier             1  0.000412

### Random Forest

In [21]:
sgkf = StratifiedGroupKFold(n_splits=5)

auprc_scores = []

# get feature set from df_ranking and filter X_train
feats = df_rankings[df_rankings.median_rank <= 6.5].index
X = X_train.filter(items=feats, axis='columns')

# the model
model = RandomForestClassifier()

for train_idx, val_idx in sgkf.split(X, y_train, groups):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    # train and fit the model
    model.fit(X_tr, y_tr)
    
    # Calculate AUPRC on validation set
    preds = model.predict_proba(X_val)[:, 1]
    precision, recall, _ = precision_recall_curve(y_val, preds)
    auprc = auc(recall, precision)
    auprc_scores.append(auprc)

# need to store results w/ a column for classifier, num_features, auprc
cv_res = {'classifier' : [model.__class__.__name__]*5,
          'num_features' : [len(feats)]*5,
          'auprc' : auprc_scores}

df_cv_res = pd.DataFrame(data=cv_res)
df_cv_res

               classifier  num_features     auprc
0  RandomForestClassifier             1  0.000195
1  RandomForestClassifier             1  0.000195
2  RandomForestClassifier             1  0.000195
3  RandomForestClassifier             1  0.000213
4  RandomForestClassifier             1  0.000195

### Extremely Randomized Trees

In [22]:
sgkf = StratifiedGroupKFold(n_splits=5)

auprc_scores = []

# get feature set from df_ranking and filter X_train
feats = df_rankings[df_rankings.median_rank <= 6.5].index
X = X_train.filter(items=feats, axis='columns')

# the model
model = ExtraTreesClassifier(n_estimators=100)

for train_idx, val_idx in sgkf.split(X, y_train, groups):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    # train and fit the model
    model.fit(X_tr, y_tr)
    
    # Calculate AUPRC on validation set
    preds = model.predict_proba(X_val)[:, 1]
    precision, recall, _ = precision_recall_curve(y_val, preds)
    auprc = auc(recall, precision)
    auprc_scores.append(auprc)

# need to store results w/ a column for classifier, num_features, auprc
cv_res = {'classifier' : [model.__class__.__name__]*5,
          'num_features' : [len(feats)]*5,
          'auprc' : auprc_scores}

df_cv_res = pd.DataFrame(data=cv_res)
df_cv_res

             classifier  num_features     auprc
0  ExtraTreesClassifier             1  0.000195
1  ExtraTreesClassifier             1  0.000195
2  ExtraTreesClassifier             1  0.000195
3  ExtraTreesClassifier             1  0.000213
4  ExtraTreesClassifier             1  0.000195

### LightGBM

In [24]:
sgkf = StratifiedGroupKFold(n_splits=5)

auprc_scores = []

# get feature set from df_ranking and filter X_train
feats = df_rankings[df_rankings.median_rank <= 6.5].index
X = X_train.filter(items=feats, axis='columns')

# the model
model = lgb.LGBMClassifier()

for train_idx, val_idx in sgkf.split(X, y_train, groups):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    # train and fit the model
    model.fit(X_tr, y_tr)
    
    # Calculate AUPRC on validation set
    preds = model.predict_proba(X_val)[:, 1]
    precision, recall, _ = precision_recall_curve(y_val, preds)
    auprc = auc(recall, precision)
    auprc_scores.append(auprc)

# need to store results w/ a column for classifier, num_features, auprc
cv_res = {'classifier' : [model.__class__.__name__]*5,
          'num_features' : [len(feats)]*5,
          'auprc' : auprc_scores}

df_cv_res = pd.DataFrame(data=cv_res)
df_cv_res

[LightGBM] [Info] Number of positive: 45, number of negative: 112616
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002777 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112661, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825077
[LightGBM] [Info] Start training from score -7.825077
[LightGBM] [Info] Number of positive: 45, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112662, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825085
[LightGBM] [Info] Start training from score -7.825085
[LightGBM] [Info] Number of positive: 45, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000237 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112662, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825085
[LightGBM] [Info] Start training from score -7.825085
[LightGBM] [Info] Number of positive: 44, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000165 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112661, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000391 -> initscore=-7.847558
[LightGBM] [Info] Start training from score -7.847558
[LightGBM] [Info] Number of positive: 45, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000430 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112662, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825085
[LightGBM] [Info] Start training from score -7.825085

       classifier  num_features     auprc
0  LGBMClassifier             1  0.000298
1  LGBMClassifier             1  0.000364
2  LGBMClassifier             1  0.000409
3  LGBMClassifier             1  0.000314
4  LGBMClassifier             1  0.000369

### Decision Tree

In [25]:
sgkf = StratifiedGroupKFold(n_splits=5)

auprc_scores = []

# get feature set from df_ranking and filter X_train
feats = df_rankings[df_rankings.median_rank <= 6.5].index
X = X_train.filter(items=feats, axis='columns')

# the model
model = DecisionTreeClassifier()

for train_idx, val_idx in sgkf.split(X, y_train, groups):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    # train and fit the model
    model.fit(X_tr, y_tr)
    
    # Calculate AUPRC on validation set
    preds = model.predict_proba(X_val)[:, 1]
    precision, recall, _ = precision_recall_curve(y_val, preds)
    auprc = auc(recall, precision)
    auprc_scores.append(auprc)

# need to store results w/ a column for classifier, num_features, auprc
cv_res = {'classifier' : [model.__class__.__name__]*5,
          'num_features' : [len(feats)]*5,
          'auprc' : auprc_scores}

df_cv_res = pd.DataFrame(data=cv_res)
df_cv_res

               classifier  num_features     auprc
0  DecisionTreeClassifier             1  0.000195
1  DecisionTreeClassifier             1  0.000195
2  DecisionTreeClassifier             1  0.000195
3  DecisionTreeClassifier             1  0.000213
4  DecisionTreeClassifier             1  0.000195

## Iterate through the models with a for loop

In [10]:
# init the base learners
# NOTE: we will need to recover the random states in the final algorithm
catboost = CatBoostClassifier(iterations=100, eval_metric='PRAUC', verbose=0)
xgb = XGBClassifier(eval_metric='aucpr')
rf = RandomForestClassifier()
et = ExtraTreesClassifier(n_estimators=100)
lgbm = lgb.LGBMClassifier()
dt = DecisionTreeClassifier()

# gather them
classifier_array = [catboost, xgb, rf, et, lgbm, dt]

sgkf = StratifiedGroupKFold(n_splits=5)

df_all_cv_res = pd.DataFrame(columns=['classifier','num_features','auprc']) # empty dataframe to put results in

# get feature set from df_ranking and filter X_train
# NOTE: iterate through all median rank values in final algorithm
feats = df_rankings[df_rankings.median_rank <= 6.5].index
X = X_train.filter(items=feats, axis='columns')

for model in classifier_array:
    auprc_scores = []
    
    for train_idx, val_idx in sgkf.split(X, y_train, groups):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

        if model.__class__.__name__ == 'XGBClassifier':
            # train and fit the model
            model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)]) # eval_set needs to be a list for XGBoost
            # Calculate AUPRC on validation set
            preds = model.predict_proba(X_val)[:, 1]
            auprc = average_precision_score(y_val, preds)
            auprc_scores.append(auprc)
            
        else:
            if model.__class__.__name__ == 'CatBoostClassifier':
                # train and fit the model
                model.fit(X_tr, y_tr, eval_set=(X_val, y_val))
            else:
                # train and fit the model
                model.fit(X_tr, y_tr)
            # Calculate AUPRC on validation set
            preds = model.predict_proba(X_val)[:, 1]
            precision, recall, _ = precision_recall_curve(y_val, preds)
            auprc = auc(recall, precision)
            auprc_scores.append(auprc)
    
    # need to store results w/ a column for classifier, num_features, auprc
    cv_res = {'classifier' : [model.__class__.__name__]*5,
              'num_features' : [len(feats)]*5,
              'auprc' : auprc_scores}
    df_cv_res = pd.DataFrame(data=cv_res)
    df_all_cv_res = pd.concat([df_all_cv_res, df_cv_res]).reset_index(drop=True)

C:\Users\camka\AppData\Local\Temp\ipykernel_22072\916417795.py:55: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all_cv_res = pd.concat([df_all_cv_res, df_cv_res])

[0]	validation_0-aucpr:0.00046
[1]	validation_0-aucpr:0.00042
[2]	validation_0-aucpr:0.00037
[3]	validation_0-aucpr:0.00036
[4]	validation_0-aucpr:0.00033
[5]	validation_0-aucpr:0.00033
[6]	validation_0-aucpr:0.00033
[7]	validation_0-aucpr:0.00030
[8]	validation_0-aucpr:0.00029
[9]	validation_0-aucpr:0.00031
[10]	validation_0-aucpr:0.00031
[11]	validation_0-aucpr:0.00029
[12]	validation_0-aucpr:0.00029
[13]	validation_0-aucpr:0.00029
[14]	validation_0-aucpr:0.00029
[15]	validation_0-aucpr:0.00029
[16]	validation_0-aucpr:0.00028
[17]	validation_0-aucpr:0.00028
[18]	validation_0-aucpr:0.00028
[19]	validation_0-aucpr:0.00028
[20]	validation_0-aucpr:0.00029
[21]	validation_0-aucpr:0.00028
[22]	validation_0-aucpr:0.00028
[23]	validation_0-aucpr:0.00028
[24]	validation_0-aucpr:0.00028
[25]	validation_0-aucpr:0.00029
[26]	validation_0-aucpr:0.00028
[27]	validation_0-aucpr:0.00028
[28]	validation_0-aucpr:0.00028
[29]	validation_0-aucpr:0.00028
[30]	validation_0-aucpr:0.00028
[31]	validation_0-aucpr:0.00028
[32]	validation_0-aucpr:0.00028
[33]	validation_0-aucpr:0.00028
[34]	validation_0-aucpr:0.00028
[35]	validation_0-aucpr:0.00028
[36]	validation_0-aucpr:0.00028
[37]	validation_0-aucpr:0.00028
[38]	validation_0-aucpr:0.00028
[39]	validation_0-aucpr:0.00028
[40]	validation_0-aucpr:0.00028
[41]	validation_0-aucpr:0.00028
[42]	validation_0-aucpr:0.00028
[43]	validation_0-aucpr:0.00028
[44]	validation_0-aucpr:0.00028
[45]	validation_0-aucpr:0.00028
[46]	validation_0-aucpr:0.00028
[47]	validation_0-aucpr:0.00028
[48]	validation_0-aucpr:0.00028
[49]	validation_0-aucpr:0.00028
[50]	validation_0-aucpr:0.00028
[51]	validation_0-aucpr:0.00028
[52]	validation_0-aucpr:0.00028
[53]	validation_0-aucpr:0.00029
[54]	validation_0-aucpr:0.00028
[55]	validation_0-aucpr:0.00028
[56]	validation_0-aucpr:0.00028
[57]	validation_0-aucpr:0.00028
[58]	validation_0-aucpr:0.00028
[59]	validation_0-aucpr:0.00028
[60]	validation_0-aucpr:0.00029
[61]	validation_0-aucpr:0.00028
[62]	validation_0-aucpr:0.00029
[63]	validation_0-aucpr:0.00029
[64]	validation_0-aucpr:0.00029
[65]	validation_0-aucpr:0.00029
[66]	validation_0-aucpr:0.00029
[67]	validation_0-aucpr:0.00029
[68]	validation_0-aucpr:0.00029
[69]	validation_0-aucpr:0.00029
[70]	validation_0-aucpr:0.00029
[71]	validation_0-aucpr:0.00029
[72]	validation_0-aucpr:0.00029
[73]	validation_0-aucpr:0.00029
[74]	validation_0-aucpr:0.00029
[75]	validation_0-aucpr:0.00029
[76]	validation_0-aucpr:0.00029
[77]	validation_0-aucpr:0.00029
[78]	validation_0-aucpr:0.00029
[79]	validation_0-aucpr:0.00029
[80]	validation_0-aucpr:0.00029
[81]	validation_0-aucpr:0.00029
[82]	validation_0-aucpr:0.00029
[83]	validation_0-aucpr:0.00029
[84]	validation_0-aucpr:0.00029
[85]	validation_0-aucpr:0.00029
[86]	validation_0-aucpr:0.00029
[87]	validation_0-aucpr:0.00029
[88]	validation_0-aucpr:0.00029
[89]	validation_0-aucpr:0.00030
[90]	validation_0-aucpr:0.00029
[91]	validation_0-aucpr:0.00029
[92]	validation_0-aucpr:0.00029
[93]	validation_0-aucpr:0.00029
[94]	validation_0-aucpr:0.00029
[95]	validation_0-aucpr:0.00029
[96]	validation_0-aucpr:0.00029
[97]	validation_0-aucpr:0.00029
[98]	validation_0-aucpr:0.00029
[99]	validation_0-aucpr:0.00029
[0]	validation_0-aucpr:0.00037
[1]	validation_0-aucpr:0.00040
[2]	validation_0-aucpr:0.00044
[3]	validation_0-aucpr:0.00055
[4]	validation_0-aucpr:0.00052
[5]	validation_0-aucpr:0.00053
[6]	validation_0-aucpr:0.00055
[7]	validation_0-aucpr:0.00057
[8]	validation_0-aucpr:0.00044
[9]	validation_0-aucpr:0.00042
[10]	validation_0-aucpr:0.00042
[11]	validation_0-aucpr:0.00041
[12]	validation_0-aucpr:0.00040
[13]	validation_0-aucpr:0.00040
[14]	validation_0-aucpr:0.00038
[15]	validation_0-aucpr:0.00039
[16]	validation_0-aucpr:0.00038
[17]	validation_0-aucpr:0.00038
[18]	validation_0-aucpr:0.00039
[19]	validation_0-aucpr:0.00037
[20]	validation_0-aucpr:0.00038
[21]	validation_0-aucpr:0.00040
[22]	validation_0-aucpr:0.00036
[23]	validation_0-aucpr:0.00036
[24]	validation_0-aucpr:0.00036
[25]	validation_0-aucpr:0.00036
[26]	validation_0-aucpr:0.00034
[27]	validation_0-aucpr:0.00035
[28]	validation_0-aucpr:0.00033
[29]	validation_0-aucpr:0.00032
[30]	validation_0-aucpr:0.00033
[31]	validation_0-aucpr:0.00033
[32]	validation_0-aucpr:0.00034
[33]	validation_0-aucpr:0.00034
[34]	validation_0-aucpr:0.00033
[35]	validation_0-aucpr:0.00033
[36]	validation_0-aucpr:0.00033
[37]	validation_0-aucpr:0.00033
[38]	validation_0-aucpr:0.00033
[39]	validation_0-aucpr:0.00032
[40]	validation_0-aucpr:0.00033
[41]	validation_0-aucpr:0.00032
[42]	validation_0-aucpr:0.00032
[43]	validation_0-aucpr:0.00032
[44]	validation_0-aucpr:0.00032
[45]	validation_0-aucpr:0.00031
[46]	validation_0-aucpr:0.00032
[47]	validation_0-aucpr:0.00031
[48]	validation_0-aucpr:0.00031
[49]	validation_0-aucpr:0.00031
[50]	validation_0-aucpr:0.00031
[51]	validation_0-aucpr:0.00031
[52]	validation_0-aucpr:0.00031
[53]	validation_0-aucpr:0.00031
[54]	validation_0-aucpr:0.00031
[55]	validation_0-aucpr:0.00031
[56]	validation_0-aucpr:0.00031
[57]	validation_0-aucpr:0.00031
[58]	validation_0-aucpr:0.00030
[59]	validation_0-aucpr:0.00030
[60]	validation_0-aucpr:0.00031
[61]	validation_0-aucpr:0.00031
[62]	validation_0-aucpr:0.00031
[63]	validation_0-aucpr:0.00031
[64]	validation_0-aucpr:0.00031
[65]	validation_0-aucpr:0.00031
[66]	validation_0-aucpr:0.00031
[67]	validation_0-aucpr:0.00031
[68]	validation_0-aucpr:0.00031
[69]	validation_0-aucpr:0.00031
[70]	validation_0-aucpr:0.00031
[71]	validation_0-aucpr:0.00031
[72]	validation_0-aucpr:0.00031
[73]	validation_0-aucpr:0.00031
[74]	validation_0-aucpr:0.00031
[75]	validation_0-aucpr:0.00031
[76]	validation_0-aucpr:0.00031
[77]	validation_0-aucpr:0.00031
[78]	validation_0-aucpr:0.00031
[79]	validation_0-aucpr:0.00031
[80]	validation_0-aucpr:0.00031
[81]	validation_0-aucpr:0.00031
[82]	validation_0-aucpr:0.00031
[83]	validation_0-aucpr:0.00031
[84]	validation_0-aucpr:0.00030
[85]	validation_0-aucpr:0.00031
[86]	validation_0-aucpr:0.00031
[87]	validation_0-aucpr:0.00031
[88]	validation_0-aucpr:0.00031
[89]	validation_0-aucpr:0.00031
[90]	validation_0-aucpr:0.00031
[91]	validation_0-aucpr:0.00031
[92]	validation_0-aucpr:0.00031
[93]	validation_0-aucpr:0.00031
[94]	validation_0-aucpr:0.00031
[95]	validation_0-aucpr:0.00031
[96]	validation_0-aucpr:0.00031
[97]	validation_0-aucpr:0.00031
[98]	validation_0-aucpr:0.00031
[99]	validation_0-aucpr:0.00031
[0]	validation_0-aucpr:0.00032
[1]	validation_0-aucpr:0.00027
[2]	validation_0-aucpr:0.00028
[3]	validation_0-aucpr:0.00028
[4]	validation_0-aucpr:0.00029
[5]	validation_0-aucpr:0.00029
[6]	validation_0-aucpr:0.00029
[7]	validation_0-aucpr:0.00032
[8]	validation_0-aucpr:0.00033
[9]	validation_0-aucpr:0.00035
[10]	validation_0-aucpr:0.00037
[11]	validation_0-aucpr:0.00036
[12]	validation_0-aucpr:0.00037
[13]	validation_0-aucpr:0.00038
[14]	validation_0-aucpr:0.00034
[15]	validation_0-aucpr:0.00033
[16]	validation_0-aucpr:0.00035
[17]	validation_0-aucpr:0.00036
[18]	validation_0-aucpr:0.00037
[19]	validation_0-aucpr:0.00037
[20]	validation_0-aucpr:0.00037
[21]	validation_0-aucpr:0.00036
[22]	validation_0-aucpr:0.00037
[23]	validation_0-aucpr:0.00036
[24]	validation_0-aucpr:0.00035
[25]	validation_0-aucpr:0.00035
[26]	validation_0-aucpr:0.00034
[27]	validation_0-aucpr:0.00036
[28]	validation_0-aucpr:0.00037
[29]	validation_0-aucpr:0.00036
[30]	validation_0-aucpr:0.00036
[31]	validation_0-aucpr:0.00037
[32]	validation_0-aucpr:0.00037
[33]	validation_0-aucpr:0.00039
[34]	validation_0-aucpr:0.00039
[35]	validation_0-aucpr:0.00040
[36]	validation_0-aucpr:0.00040
[37]	validation_0-aucpr:0.00038
[38]	validation_0-aucpr:0.00037
[39]	validation_0-aucpr:0.00037
[40]	validation_0-aucpr:0.00038
[41]	validation_0-aucpr:0.00038
[42]	validation_0-aucpr:0.00038
[43]	validation_0-aucpr:0.00038
[44]	validation_0-aucpr:0.00039
[45]	validation_0-aucpr:0.00039
[46]	validation_0-aucpr:0.00039
[47]	validation_0-aucpr:0.00039
[48]	validation_0-aucpr:0.00040
[49]	validation_0-aucpr:0.00037
[50]	validation_0-aucpr:0.00037
[51]	validation_0-aucpr:0.00038
[52]	validation_0-aucpr:0.00038
[53]	validation_0-aucpr:0.00038
[54]	validation_0-aucpr:0.00038
[55]	validation_0-aucpr:0.00038
[56]	validation_0-aucpr:0.00038
[57]	validation_0-aucpr:0.00038
[58]	validation_0-aucpr:0.00038
[59]	validation_0-aucpr:0.00039
[60]	validation_0-aucpr:0.00039
[61]	validation_0-aucpr:0.00039
[62]	validation_0-aucpr:0.00040
[63]	validation_0-aucpr:0.00039
[64]	validation_0-aucpr:0.00040
[65]	validation_0-aucpr:0.00040
[66]	validation_0-aucpr:0.00040
[67]	validation_0-aucpr:0.00040
[68]	validation_0-aucpr:0.00040
[69]	validation_0-aucpr:0.00040
[70]	validation_0-aucpr:0.00040
[71]	validation_0-aucpr:0.00041
[72]	validation_0-aucpr:0.00041
[73]	validation_0-aucpr:0.00041
[74]	validation_0-aucpr:0.00042
[75]	validation_0-aucpr:0.00043
[76]	validation_0-aucpr:0.00042
[77]	validation_0-aucpr:0.00042
[78]	validation_0-aucpr:0.00041
[79]	validation_0-aucpr:0.00040
[80]	validation_0-aucpr:0.00041
[81]	validation_0-aucpr:0.00041
[82]	validation_0-aucpr:0.00042
[83]	validation_0-aucpr:0.00041
[84]	validation_0-aucpr:0.00042
[85]	validation_0-aucpr:0.00042
[86]	validation_0-aucpr:0.00042
[87]	validation_0-aucpr:0.00042
[88]	validation_0-aucpr:0.00041
[89]	validation_0-aucpr:0.00041
[90]	validation_0-aucpr:0.00042
[91]	validation_0-aucpr:0.00043
[92]	validation_0-aucpr:0.00043
[93]	validation_0-aucpr:0.00042
[94]	validation_0-aucpr:0.00042
[95]	validation_0-aucpr:0.00042
[96]	validation_0-aucpr:0.00043
[97]	validation_0-aucpr:0.00043
[98]	validation_0-aucpr:0.00044
[99]	validation_0-aucpr:0.00044
[0]	validation_0-aucpr:0.00029
[1]	validation_0-aucpr:0.00030
[2]	validation_0-aucpr:0.00029
[3]	validation_0-aucpr:0.00029
[4]	validation_0-aucpr:0.00028
[5]	validation_0-aucpr:0.00028
[6]	validation_0-aucpr:0.00029
[7]	validation_0-aucpr:0.00031
[8]	validation_0-aucpr:0.00030
[9]	validation_0-aucpr:0.00033
[10]	validation_0-aucpr:0.00031
[11]	validation_0-aucpr:0.00031
[12]	validation_0-aucpr:0.00031
[13]	validation_0-aucpr:0.00031
[14]	validation_0-aucpr:0.00030
[15]	validation_0-aucpr:0.00030
[16]	validation_0-aucpr:0.00031
[17]	validation_0-aucpr:0.00032
[18]	validation_0-aucpr:0.00032
[19]	validation_0-aucpr:0.00031
[20]	validation_0-aucpr:0.00033
[21]	validation_0-aucpr:0.00034
[22]	validation_0-aucpr:0.00033
[23]	validation_0-aucpr:0.00033
[24]	validation_0-aucpr:0.00032
[25]	validation_0-aucpr:0.00032
[26]	validation_0-aucpr:0.00032
[27]	validation_0-aucpr:0.00033
[28]	validation_0-aucpr:0.00032
[29]	validation_0-aucpr:0.00033
[30]	validation_0-aucpr:0.00033
[31]	validation_0-aucpr:0.00032
[32]	validation_0-aucpr:0.00032
[33]	validation_0-aucpr:0.00032
[34]	validation_0-aucpr:0.00032
[35]	validation_0-aucpr:0.00031
[36]	validation_0-aucpr:0.00031
[37]	validation_0-aucpr:0.00032
[38]	validation_0-aucpr:0.00032
[39]	validation_0-aucpr:0.00032
[40]	validation_0-aucpr:0.00032
[41]	validation_0-aucpr:0.00032
[42]	validation_0-aucpr:0.00032
[43]	validation_0-aucpr:0.00032
[44]	validation_0-aucpr:0.00032
[45]	validation_0-aucpr:0.00032
[46]	validation_0-aucpr:0.00031
[47]	validation_0-aucpr:0.00032
[48]	validation_0-aucpr:0.00032
[49]	validation_0-aucpr:0.00032
[50]	validation_0-aucpr:0.00032
[51]	validation_0-aucpr:0.00031
[52]	validation_0-aucpr:0.00032
[53]	validation_0-aucpr:0.00031
[54]	validation_0-aucpr:0.00032
[55]	validation_0-aucpr:0.00032
[56]	validation_0-aucpr:0.00032
[57]	validation_0-aucpr:0.00032
[58]	validation_0-aucpr:0.00032
[59]	validation_0-aucpr:0.00031
[60]	validation_0-aucpr:0.00031
[61]	validation_0-aucpr:0.00031
[62]	validation_0-aucpr:0.00032
[63]	validation_0-aucpr:0.00031
[64]	validation_0-aucpr:0.00031
[65]	validation_0-aucpr:0.00031
[66]	validation_0-aucpr:0.00031
[67]	validation_0-aucpr:0.00031
[68]	validation_0-aucpr:0.00030
[69]	validation_0-aucpr:0.00031
[70]	validation_0-aucpr:0.00030
[71]	validation_0-aucpr:0.00031
[72]	validation_0-aucpr:0.00031
[73]	validation_0-aucpr:0.00031
[74]	validation_0-aucpr:0.00031
[75]	validation_0-aucpr:0.00031
[76]	validation_0-aucpr:0.00031
[77]	validation_0-aucpr:0.00031
[78]	validation_0-aucpr:0.00031
[79]	validation_0-aucpr:0.00031
[80]	validation_0-aucpr:0.00030
[81]	validation_0-aucpr:0.00031
[82]	validation_0-aucpr:0.00031
[83]	validation_0-aucpr:0.00031
[84]	validation_0-aucpr:0.00031
[85]	validation_0-aucpr:0.00030
[86]	validation_0-aucpr:0.00031
[87]	validation_0-aucpr:0.00030
[88]	validation_0-aucpr:0.00031
[89]	validation_0-aucpr:0.00031
[90]	validation_0-aucpr:0.00031
[91]	validation_0-aucpr:0.00031
[92]	validation_0-aucpr:0.00031
[93]	validation_0-aucpr:0.00031
[94]	validation_0-aucpr:0.00031
[95]	validation_0-aucpr:0.00031
[96]	validation_0-aucpr:0.00031
[97]	validation_0-aucpr:0.00031
[98]	validation_0-aucpr:0.00031
[99]	validation_0-aucpr:0.00030
[0]	validation_0-aucpr:0.00027
[1]	validation_0-aucpr:0.00028
[2]	validation_0-aucpr:0.00029
[3]	validation_0-aucpr:0.00029
[4]	validation_0-aucpr:0.00029
[5]	validation_0-aucpr:0.00028
[6]	validation_0-aucpr:0.00028
[7]	validation_0-aucpr:0.00029
[8]	validation_0-aucpr:0.00029
[9]	validation_0-aucpr:0.00029
[10]	validation_0-aucpr:0.00030
[11]	validation_0-aucpr:0.00030
[12]	validation_0-aucpr:0.00030
[13]	validation_0-aucpr:0.00029
[14]	validation_0-aucpr:0.00029
[15]	validation_0-aucpr:0.00028
[16]	validation_0-aucpr:0.00030
[17]	validation_0-aucpr:0.00030
[18]	validation_0-aucpr:0.00031
[19]	validation_0-aucpr:0.00031
[20]	validation_0-aucpr:0.00031
[21]	validation_0-aucpr:0.00032
[22]	validation_0-aucpr:0.00031
[23]	validation_0-aucpr:0.00029
[24]	validation_0-aucpr:0.00030
[25]	validation_0-aucpr:0.00034
[26]	validation_0-aucpr:0.00032
[27]	validation_0-aucpr:0.00030
[28]	validation_0-aucpr:0.00030
[29]	validation_0-aucpr:0.00031
[30]	validation_0-aucpr:0.00031
[31]	validation_0-aucpr:0.00031
[32]	validation_0-aucpr:0.00032
[33]	validation_0-aucpr:0.00032
[34]	validation_0-aucpr:0.00030
[35]	validation_0-aucpr:0.00030
[36]	validation_0-aucpr:0.00030
[37]	validation_0-aucpr:0.00030
[38]	validation_0-aucpr:0.00030
[39]	validation_0-aucpr:0.00032
[40]	validation_0-aucpr:0.00032
[41]	validation_0-aucpr:0.00032
[42]	validation_0-aucpr:0.00032
[43]	validation_0-aucpr:0.00031
[44]	validation_0-aucpr:0.00031
[45]	validation_0-aucpr:0.00031
[46]	validation_0-aucpr:0.00032
[47]	validation_0-aucpr:0.00032
[48]	validation_0-aucpr:0.00032
[49]	validation_0-aucpr:0.00032
[50]	validation_0-aucpr:0.00032
[51]	validation_0-aucpr:0.00032
[52]	validation_0-aucpr:0.00032
[53]	validation_0-aucpr:0.00033
[54]	validation_0-aucpr:0.00033
[55]	validation_0-aucpr:0.00034
[56]	validation_0-aucpr:0.00034
[57]	validation_0-aucpr:0.00034
[58]	validation_0-aucpr:0.00034
[59]	validation_0-aucpr:0.00034
[60]	validation_0-aucpr:0.00034
[61]	validation_0-aucpr:0.00035
[62]	validation_0-aucpr:0.00034
[63]	validation_0-aucpr:0.00035
[64]	validation_0-aucpr:0.00033
[65]	validation_0-aucpr:0.00035
[66]	validation_0-aucpr:0.00035
[67]	validation_0-aucpr:0.00035
[68]	validation_0-aucpr:0.00035
[69]	validation_0-aucpr:0.00034
[70]	validation_0-aucpr:0.00035
[71]	validation_0-aucpr:0.00035
[72]	validation_0-aucpr:0.00035
[73]	validation_0-aucpr:0.00036
[74]	validation_0-aucpr:0.00036
[75]	validation_0-aucpr:0.00036
[76]	validation_0-aucpr:0.00035
[77]	validation_0-aucpr:0.00036
[78]	validation_0-aucpr:0.00036
[79]	validation_0-aucpr:0.00036
[80]	validation_0-aucpr:0.00036
[81]	validation_0-aucpr:0.00036
[82]	validation_0-aucpr:0.00036
[83]	validation_0-aucpr:0.00036
[84]	validation_0-aucpr:0.00036
[85]	validation_0-aucpr:0.00036
[86]	validation_0-aucpr:0.00036
[87]	validation_0-aucpr:0.00036
[88]	validation_0-aucpr:0.00036
[89]	validation_0-aucpr:0.00036
[90]	validation_0-aucpr:0.00036
[91]	validation_0-aucpr:0.00035
[92]	validation_0-aucpr:0.00034
[93]	validation_0-aucpr:0.00034
[94]	validation_0-aucpr:0.00036
[95]	validation_0-aucpr:0.00036
[96]	validation_0-aucpr:0.00036
[97]	validation_0-aucpr:0.00036
[98]	validation_0-aucpr:0.00036
[99]	validation_0-aucpr:0.00036
[LightGBM] [Info] Number of positive: 45, number of negative: 112616
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000642 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112661, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825077
[LightGBM] [Info] Start training from score -7.825077
[LightGBM] [Info] Number of positive: 45, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000159 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112662, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825085
[LightGBM] [Info] Start training from score -7.825085
[LightGBM] [Info] Number of positive: 45, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000156 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112662, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825085
[LightGBM] [Info] Start training from score -7.825085
[LightGBM] [Info] Number of positive: 44, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000300 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112661, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000391 -> initscore=-7.847558
[LightGBM] [Info] Start training from score -7.847558
[LightGBM] [Info] Number of positive: 45, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000308 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112662, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825085
[LightGBM] [Info] Start training from score -7.825085

In [ ]:
df_all_cv_res

## Turn the 5-fold CV subroutine into a function

In [12]:
def sgkf_cv(model, X, y_train, groups, n_splits=5):
    """Does stratified group k-fold cross validation where k=n_splits (default 5)
    then returns an array of scores with length n_splits."""
    sgkf=StratifiedGroupKFold(n_splits=n_splits)
    auprc_scores = []
    for train_idx, val_idx in sgkf.split(X, y_train, groups):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]
        if model.__class__.__name__ == 'XGBClassifier':
            # train and fit the model
            model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)]) # eval_set needs to be a list for XGBoost
            # Calculate AUPRC on validation set
            preds = model.predict_proba(X_val)[:, 1]
            auprc = average_precision_score(y_val, preds)
            auprc_scores.append(auprc)
        else:
            if model.__class__.__name__ == 'CatBoostClassifier':
                # train and fit the model
                model.fit(X_tr, y_tr, eval_set=(X_val, y_val))
            else:
                # train and fit the model
                model.fit(X_tr, y_tr)
            # Calculate AUPRC on validation set
            preds = model.predict_proba(X_val)[:, 1]
            precision, recall, _ = precision_recall_curve(y_val, preds)
            auprc = auc(recall, precision)
            auprc_scores.append(auprc)
    return auprc_scores

In [14]:
# init the base learners
# NOTE: we will need to recover the random states in the final algorithm
catboost = CatBoostClassifier(iterations=100, eval_metric='PRAUC', verbose=0)
xgb = XGBClassifier(eval_metric='aucpr')
rf = RandomForestClassifier()
et = ExtraTreesClassifier(n_estimators=100)
lgbm = lgb.LGBMClassifier()
dt = DecisionTreeClassifier()

# gather them
classifier_array = [catboost, xgb, rf, et, lgbm, dt]

sgkf = StratifiedGroupKFold(n_splits=5)

df_all_cv_res = pd.DataFrame(columns=['classifier','num_features','auprc']) # empty dataframe to put results in

# get feature set from df_ranking and filter X_train
# NOTE: iterate through all median rank values in final algorithm
feats = df_rankings[df_rankings.median_rank <= 6.5].index
X = X_train.filter(items=feats, axis='columns')

for model in classifier_array:
    n_splits = 5
    auprc_scores = sgkf_cv(model, X, y_train, groups, n_splits=n_splits)
    # need to store results w/ a column for classifier, num_features, auprc
    cv_res = {'classifier' : [model.__class__.__name__]*n_splits,
              'num_features' : [len(feats)]*n_splits,
              'auprc' : auprc_scores}
    df_cv_res = pd.DataFrame(data=cv_res)
    df_all_cv_res = pd.concat([df_all_cv_res, df_cv_res]).reset_index(drop=True)

C:\Users\camka\AppData\Local\Temp\ipykernel_22072\3164419889.py:30: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all_cv_res = pd.concat([df_all_cv_res, df_cv_res]).reset_index(drop=True)

[0]	validation_0-aucpr:0.00046
[1]	validation_0-aucpr:0.00042
[2]	validation_0-aucpr:0.00037
[3]	validation_0-aucpr:0.00036
[4]	validation_0-aucpr:0.00033
[5]	validation_0-aucpr:0.00033
[6]	validation_0-aucpr:0.00033
[7]	validation_0-aucpr:0.00030
[8]	validation_0-aucpr:0.00029
[9]	validation_0-aucpr:0.00031
[10]	validation_0-aucpr:0.00031
[11]	validation_0-aucpr:0.00029
[12]	validation_0-aucpr:0.00029
[13]	validation_0-aucpr:0.00029
[14]	validation_0-aucpr:0.00029
[15]	validation_0-aucpr:0.00029
[16]	validation_0-aucpr:0.00028
[17]	validation_0-aucpr:0.00028
[18]	validation_0-aucpr:0.00028
[19]	validation_0-aucpr:0.00028
[20]	validation_0-aucpr:0.00029
[21]	validation_0-aucpr:0.00028
[22]	validation_0-aucpr:0.00028
[23]	validation_0-aucpr:0.00028
[24]	validation_0-aucpr:0.00028
[25]	validation_0-aucpr:0.00029
[26]	validation_0-aucpr:0.00028
[27]	validation_0-aucpr:0.00028
[28]	validation_0-aucpr:0.00028
[29]	validation_0-aucpr:0.00028
[30]	validation_0-aucpr:0.00028
[31]	validation_0-aucpr:0.00028
[32]	validation_0-aucpr:0.00028
[33]	validation_0-aucpr:0.00028
[34]	validation_0-aucpr:0.00028
[35]	validation_0-aucpr:0.00028
[36]	validation_0-aucpr:0.00028
[37]	validation_0-aucpr:0.00028
[38]	validation_0-aucpr:0.00028
[39]	validation_0-aucpr:0.00028
[40]	validation_0-aucpr:0.00028
[41]	validation_0-aucpr:0.00028
[42]	validation_0-aucpr:0.00028
[43]	validation_0-aucpr:0.00028
[44]	validation_0-aucpr:0.00028
[45]	validation_0-aucpr:0.00028
[46]	validation_0-aucpr:0.00028
[47]	validation_0-aucpr:0.00028
[48]	validation_0-aucpr:0.00028
[49]	validation_0-aucpr:0.00028
[50]	validation_0-aucpr:0.00028
[51]	validation_0-aucpr:0.00028
[52]	validation_0-aucpr:0.00028
[53]	validation_0-aucpr:0.00029
[54]	validation_0-aucpr:0.00028
[55]	validation_0-aucpr:0.00028
[56]	validation_0-aucpr:0.00028
[57]	validation_0-aucpr:0.00028
[58]	validation_0-aucpr:0.00028
[59]	validation_0-aucpr:0.00028
[60]	validation_0-aucpr:0.00029
[61]	validation_0-aucpr:0.00028
[62]	validation_0-aucpr:0.00029
[63]	validation_0-aucpr:0.00029
[64]	validation_0-aucpr:0.00029
[65]	validation_0-aucpr:0.00029
[66]	validation_0-aucpr:0.00029
[67]	validation_0-aucpr:0.00029
[68]	validation_0-aucpr:0.00029
[69]	validation_0-aucpr:0.00029
[70]	validation_0-aucpr:0.00029
[71]	validation_0-aucpr:0.00029
[72]	validation_0-aucpr:0.00029
[73]	validation_0-aucpr:0.00029
[74]	validation_0-aucpr:0.00029
[75]	validation_0-aucpr:0.00029
[76]	validation_0-aucpr:0.00029
[77]	validation_0-aucpr:0.00029
[78]	validation_0-aucpr:0.00029
[79]	validation_0-aucpr:0.00029
[80]	validation_0-aucpr:0.00029
[81]	validation_0-aucpr:0.00029
[82]	validation_0-aucpr:0.00029
[83]	validation_0-aucpr:0.00029
[84]	validation_0-aucpr:0.00029
[85]	validation_0-aucpr:0.00029
[86]	validation_0-aucpr:0.00029
[87]	validation_0-aucpr:0.00029
[88]	validation_0-aucpr:0.00029
[89]	validation_0-aucpr:0.00030
[90]	validation_0-aucpr:0.00029
[91]	validation_0-aucpr:0.00029
[92]	validation_0-aucpr:0.00029
[93]	validation_0-aucpr:0.00029
[94]	validation_0-aucpr:0.00029
[95]	validation_0-aucpr:0.00029
[96]	validation_0-aucpr:0.00029
[97]	validation_0-aucpr:0.00029
[98]	validation_0-aucpr:0.00029
[99]	validation_0-aucpr:0.00029
[0]	validation_0-aucpr:0.00037
[1]	validation_0-aucpr:0.00040
[2]	validation_0-aucpr:0.00044
[3]	validation_0-aucpr:0.00055
[4]	validation_0-aucpr:0.00052
[5]	validation_0-aucpr:0.00053
[6]	validation_0-aucpr:0.00055
[7]	validation_0-aucpr:0.00057
[8]	validation_0-aucpr:0.00044
[9]	validation_0-aucpr:0.00042
[10]	validation_0-aucpr:0.00042
[11]	validation_0-aucpr:0.00041
[12]	validation_0-aucpr:0.00040
[13]	validation_0-aucpr:0.00040
[14]	validation_0-aucpr:0.00038
[15]	validation_0-aucpr:0.00039
[16]	validation_0-aucpr:0.00038
[17]	validation_0-aucpr:0.00038
[18]	validation_0-aucpr:0.00039
[19]	validation_0-aucpr:0.00037
[20]	validation_0-aucpr:0.00038
[21]	validation_0-aucpr:0.00040
[22]	validation_0-aucpr:0.00036
[23]	validation_0-aucpr:0.00036
[24]	validation_0-aucpr:0.00036
[25]	validation_0-aucpr:0.00036
[26]	validation_0-aucpr:0.00034
[27]	validation_0-aucpr:0.00035
[28]	validation_0-aucpr:0.00033
[29]	validation_0-aucpr:0.00032
[30]	validation_0-aucpr:0.00033
[31]	validation_0-aucpr:0.00033
[32]	validation_0-aucpr:0.00034
[33]	validation_0-aucpr:0.00034
[34]	validation_0-aucpr:0.00033
[35]	validation_0-aucpr:0.00033
[36]	validation_0-aucpr:0.00033
[37]	validation_0-aucpr:0.00033
[38]	validation_0-aucpr:0.00033
[39]	validation_0-aucpr:0.00032
[40]	validation_0-aucpr:0.00033
[41]	validation_0-aucpr:0.00032
[42]	validation_0-aucpr:0.00032
[43]	validation_0-aucpr:0.00032
[44]	validation_0-aucpr:0.00032
[45]	validation_0-aucpr:0.00031
[46]	validation_0-aucpr:0.00032
[47]	validation_0-aucpr:0.00031
[48]	validation_0-aucpr:0.00031
[49]	validation_0-aucpr:0.00031
[50]	validation_0-aucpr:0.00031
[51]	validation_0-aucpr:0.00031
[52]	validation_0-aucpr:0.00031
[53]	validation_0-aucpr:0.00031
[54]	validation_0-aucpr:0.00031
[55]	validation_0-aucpr:0.00031
[56]	validation_0-aucpr:0.00031
[57]	validation_0-aucpr:0.00031
[58]	validation_0-aucpr:0.00030
[59]	validation_0-aucpr:0.00030
[60]	validation_0-aucpr:0.00031
[61]	validation_0-aucpr:0.00031
[62]	validation_0-aucpr:0.00031
[63]	validation_0-aucpr:0.00031
[64]	validation_0-aucpr:0.00031
[65]	validation_0-aucpr:0.00031
[66]	validation_0-aucpr:0.00031
[67]	validation_0-aucpr:0.00031
[68]	validation_0-aucpr:0.00031
[69]	validation_0-aucpr:0.00031
[70]	validation_0-aucpr:0.00031
[71]	validation_0-aucpr:0.00031
[72]	validation_0-aucpr:0.00031
[73]	validation_0-aucpr:0.00031
[74]	validation_0-aucpr:0.00031
[75]	validation_0-aucpr:0.00031
[76]	validation_0-aucpr:0.00031
[77]	validation_0-aucpr:0.00031
[78]	validation_0-aucpr:0.00031
[79]	validation_0-aucpr:0.00031
[80]	validation_0-aucpr:0.00031
[81]	validation_0-aucpr:0.00031
[82]	validation_0-aucpr:0.00031
[83]	validation_0-aucpr:0.00031
[84]	validation_0-aucpr:0.00030
[85]	validation_0-aucpr:0.00031
[86]	validation_0-aucpr:0.00031
[87]	validation_0-aucpr:0.00031
[88]	validation_0-aucpr:0.00031
[89]	validation_0-aucpr:0.00031
[90]	validation_0-aucpr:0.00031
[91]	validation_0-aucpr:0.00031
[92]	validation_0-aucpr:0.00031
[93]	validation_0-aucpr:0.00031
[94]	validation_0-aucpr:0.00031
[95]	validation_0-aucpr:0.00031
[96]	validation_0-aucpr:0.00031
[97]	validation_0-aucpr:0.00031
[98]	validation_0-aucpr:0.00031
[99]	validation_0-aucpr:0.00031
[0]	validation_0-aucpr:0.00032
[1]	validation_0-aucpr:0.00027
[2]	validation_0-aucpr:0.00028
[3]	validation_0-aucpr:0.00028
[4]	validation_0-aucpr:0.00029
[5]	validation_0-aucpr:0.00029
[6]	validation_0-aucpr:0.00029
[7]	validation_0-aucpr:0.00032
[8]	validation_0-aucpr:0.00033
[9]	validation_0-aucpr:0.00035
[10]	validation_0-aucpr:0.00037
[11]	validation_0-aucpr:0.00036
[12]	validation_0-aucpr:0.00037
[13]	validation_0-aucpr:0.00038
[14]	validation_0-aucpr:0.00034
[15]	validation_0-aucpr:0.00033
[16]	validation_0-aucpr:0.00035
[17]	validation_0-aucpr:0.00036
[18]	validation_0-aucpr:0.00037
[19]	validation_0-aucpr:0.00037
[20]	validation_0-aucpr:0.00037
[21]	validation_0-aucpr:0.00036
[22]	validation_0-aucpr:0.00037
[23]	validation_0-aucpr:0.00036
[24]	validation_0-aucpr:0.00035
[25]	validation_0-aucpr:0.00035
[26]	validation_0-aucpr:0.00034
[27]	validation_0-aucpr:0.00036
[28]	validation_0-aucpr:0.00037
[29]	validation_0-aucpr:0.00036
[30]	validation_0-aucpr:0.00036
[31]	validation_0-aucpr:0.00037
[32]	validation_0-aucpr:0.00037
[33]	validation_0-aucpr:0.00039
[34]	validation_0-aucpr:0.00039
[35]	validation_0-aucpr:0.00040
[36]	validation_0-aucpr:0.00040
[37]	validation_0-aucpr:0.00038
[38]	validation_0-aucpr:0.00037
[39]	validation_0-aucpr:0.00037
[40]	validation_0-aucpr:0.00038
[41]	validation_0-aucpr:0.00038
[42]	validation_0-aucpr:0.00038
[43]	validation_0-aucpr:0.00038
[44]	validation_0-aucpr:0.00039
[45]	validation_0-aucpr:0.00039
[46]	validation_0-aucpr:0.00039
[47]	validation_0-aucpr:0.00039
[48]	validation_0-aucpr:0.00040
[49]	validation_0-aucpr:0.00037
[50]	validation_0-aucpr:0.00037
[51]	validation_0-aucpr:0.00038
[52]	validation_0-aucpr:0.00038
[53]	validation_0-aucpr:0.00038
[54]	validation_0-aucpr:0.00038
[55]	validation_0-aucpr:0.00038
[56]	validation_0-aucpr:0.00038
[57]	validation_0-aucpr:0.00038
[58]	validation_0-aucpr:0.00038
[59]	validation_0-aucpr:0.00039
[60]	validation_0-aucpr:0.00039
[61]	validation_0-aucpr:0.00039
[62]	validation_0-aucpr:0.00040
[63]	validation_0-aucpr:0.00039
[64]	validation_0-aucpr:0.00040
[65]	validation_0-aucpr:0.00040
[66]	validation_0-aucpr:0.00040
[67]	validation_0-aucpr:0.00040
[68]	validation_0-aucpr:0.00040
[69]	validation_0-aucpr:0.00040
[70]	validation_0-aucpr:0.00040
[71]	validation_0-aucpr:0.00041
[72]	validation_0-aucpr:0.00041
[73]	validation_0-aucpr:0.00041
[74]	validation_0-aucpr:0.00042
[75]	validation_0-aucpr:0.00043
[76]	validation_0-aucpr:0.00042
[77]	validation_0-aucpr:0.00042
[78]	validation_0-aucpr:0.00041
[79]	validation_0-aucpr:0.00040
[80]	validation_0-aucpr:0.00041
[81]	validation_0-aucpr:0.00041
[82]	validation_0-aucpr:0.00042
[83]	validation_0-aucpr:0.00041
[84]	validation_0-aucpr:0.00042
[85]	validation_0-aucpr:0.00042
[86]	validation_0-aucpr:0.00042
[87]	validation_0-aucpr:0.00042
[88]	validation_0-aucpr:0.00041
[89]	validation_0-aucpr:0.00041
[90]	validation_0-aucpr:0.00042
[91]	validation_0-aucpr:0.00043
[92]	validation_0-aucpr:0.00043
[93]	validation_0-aucpr:0.00042
[94]	validation_0-aucpr:0.00042
[95]	validation_0-aucpr:0.00042
[96]	validation_0-aucpr:0.00043
[97]	validation_0-aucpr:0.00043
[98]	validation_0-aucpr:0.00044
[99]	validation_0-aucpr:0.00044
[0]	validation_0-aucpr:0.00029
[1]	validation_0-aucpr:0.00030
[2]	validation_0-aucpr:0.00029
[3]	validation_0-aucpr:0.00029
[4]	validation_0-aucpr:0.00028
[5]	validation_0-aucpr:0.00028
[6]	validation_0-aucpr:0.00029
[7]	validation_0-aucpr:0.00031
[8]	validation_0-aucpr:0.00030
[9]	validation_0-aucpr:0.00033
[10]	validation_0-aucpr:0.00031
[11]	validation_0-aucpr:0.00031
[12]	validation_0-aucpr:0.00031
[13]	validation_0-aucpr:0.00031
[14]	validation_0-aucpr:0.00030
[15]	validation_0-aucpr:0.00030
[16]	validation_0-aucpr:0.00031
[17]	validation_0-aucpr:0.00032
[18]	validation_0-aucpr:0.00032
[19]	validation_0-aucpr:0.00031
[20]	validation_0-aucpr:0.00033
[21]	validation_0-aucpr:0.00034
[22]	validation_0-aucpr:0.00033
[23]	validation_0-aucpr:0.00033
[24]	validation_0-aucpr:0.00032
[25]	validation_0-aucpr:0.00032
[26]	validation_0-aucpr:0.00032
[27]	validation_0-aucpr:0.00033
[28]	validation_0-aucpr:0.00032
[29]	validation_0-aucpr:0.00033
[30]	validation_0-aucpr:0.00033
[31]	validation_0-aucpr:0.00032
[32]	validation_0-aucpr:0.00032
[33]	validation_0-aucpr:0.00032
[34]	validation_0-aucpr:0.00032
[35]	validation_0-aucpr:0.00031
[36]	validation_0-aucpr:0.00031
[37]	validation_0-aucpr:0.00032
[38]	validation_0-aucpr:0.00032
[39]	validation_0-aucpr:0.00032
[40]	validation_0-aucpr:0.00032
[41]	validation_0-aucpr:0.00032
[42]	validation_0-aucpr:0.00032
[43]	validation_0-aucpr:0.00032
[44]	validation_0-aucpr:0.00032
[45]	validation_0-aucpr:0.00032
[46]	validation_0-aucpr:0.00031
[47]	validation_0-aucpr:0.00032
[48]	validation_0-aucpr:0.00032
[49]	validation_0-aucpr:0.00032
[50]	validation_0-aucpr:0.00032
[51]	validation_0-aucpr:0.00031
[52]	validation_0-aucpr:0.00032
[53]	validation_0-aucpr:0.00031
[54]	validation_0-aucpr:0.00032
[55]	validation_0-aucpr:0.00032
[56]	validation_0-aucpr:0.00032
[57]	validation_0-aucpr:0.00032
[58]	validation_0-aucpr:0.00032
[59]	validation_0-aucpr:0.00031
[60]	validation_0-aucpr:0.00031
[61]	validation_0-aucpr:0.00031
[62]	validation_0-aucpr:0.00032
[63]	validation_0-aucpr:0.00031
[64]	validation_0-aucpr:0.00031
[65]	validation_0-aucpr:0.00031
[66]	validation_0-aucpr:0.00031
[67]	validation_0-aucpr:0.00031
[68]	validation_0-aucpr:0.00030
[69]	validation_0-aucpr:0.00031
[70]	validation_0-aucpr:0.00030
[71]	validation_0-aucpr:0.00031
[72]	validation_0-aucpr:0.00031
[73]	validation_0-aucpr:0.00031
[74]	validation_0-aucpr:0.00031
[75]	validation_0-aucpr:0.00031
[76]	validation_0-aucpr:0.00031
[77]	validation_0-aucpr:0.00031
[78]	validation_0-aucpr:0.00031
[79]	validation_0-aucpr:0.00031
[80]	validation_0-aucpr:0.00030
[81]	validation_0-aucpr:0.00031
[82]	validation_0-aucpr:0.00031
[83]	validation_0-aucpr:0.00031
[84]	validation_0-aucpr:0.00031
[85]	validation_0-aucpr:0.00030
[86]	validation_0-aucpr:0.00031
[87]	validation_0-aucpr:0.00030
[88]	validation_0-aucpr:0.00031
[89]	validation_0-aucpr:0.00031
[90]	validation_0-aucpr:0.00031
[91]	validation_0-aucpr:0.00031
[92]	validation_0-aucpr:0.00031
[93]	validation_0-aucpr:0.00031
[94]	validation_0-aucpr:0.00031
[95]	validation_0-aucpr:0.00031
[96]	validation_0-aucpr:0.00031
[97]	validation_0-aucpr:0.00031
[98]	validation_0-aucpr:0.00031
[99]	validation_0-aucpr:0.00030
[0]	validation_0-aucpr:0.00027
[1]	validation_0-aucpr:0.00028
[2]	validation_0-aucpr:0.00029
[3]	validation_0-aucpr:0.00029
[4]	validation_0-aucpr:0.00029
[5]	validation_0-aucpr:0.00028
[6]	validation_0-aucpr:0.00028
[7]	validation_0-aucpr:0.00029
[8]	validation_0-aucpr:0.00029
[9]	validation_0-aucpr:0.00029
[10]	validation_0-aucpr:0.00030
[11]	validation_0-aucpr:0.00030
[12]	validation_0-aucpr:0.00030
[13]	validation_0-aucpr:0.00029
[14]	validation_0-aucpr:0.00029
[15]	validation_0-aucpr:0.00028
[16]	validation_0-aucpr:0.00030
[17]	validation_0-aucpr:0.00030
[18]	validation_0-aucpr:0.00031
[19]	validation_0-aucpr:0.00031
[20]	validation_0-aucpr:0.00031
[21]	validation_0-aucpr:0.00032
[22]	validation_0-aucpr:0.00031
[23]	validation_0-aucpr:0.00029
[24]	validation_0-aucpr:0.00030
[25]	validation_0-aucpr:0.00034
[26]	validation_0-aucpr:0.00032
[27]	validation_0-aucpr:0.00030
[28]	validation_0-aucpr:0.00030
[29]	validation_0-aucpr:0.00031
[30]	validation_0-aucpr:0.00031
[31]	validation_0-aucpr:0.00031
[32]	validation_0-aucpr:0.00032
[33]	validation_0-aucpr:0.00032
[34]	validation_0-aucpr:0.00030
[35]	validation_0-aucpr:0.00030
[36]	validation_0-aucpr:0.00030
[37]	validation_0-aucpr:0.00030
[38]	validation_0-aucpr:0.00030
[39]	validation_0-aucpr:0.00032
[40]	validation_0-aucpr:0.00032
[41]	validation_0-aucpr:0.00032
[42]	validation_0-aucpr:0.00032
[43]	validation_0-aucpr:0.00031
[44]	validation_0-aucpr:0.00031
[45]	validation_0-aucpr:0.00031
[46]	validation_0-aucpr:0.00032
[47]	validation_0-aucpr:0.00032
[48]	validation_0-aucpr:0.00032
[49]	validation_0-aucpr:0.00032
[50]	validation_0-aucpr:0.00032
[51]	validation_0-aucpr:0.00032
[52]	validation_0-aucpr:0.00032
[53]	validation_0-aucpr:0.00033
[54]	validation_0-aucpr:0.00033
[55]	validation_0-aucpr:0.00034
[56]	validation_0-aucpr:0.00034
[57]	validation_0-aucpr:0.00034
[58]	validation_0-aucpr:0.00034
[59]	validation_0-aucpr:0.00034
[60]	validation_0-aucpr:0.00034
[61]	validation_0-aucpr:0.00035
[62]	validation_0-aucpr:0.00034
[63]	validation_0-aucpr:0.00035
[64]	validation_0-aucpr:0.00033
[65]	validation_0-aucpr:0.00035
[66]	validation_0-aucpr:0.00035
[67]	validation_0-aucpr:0.00035
[68]	validation_0-aucpr:0.00035
[69]	validation_0-aucpr:0.00034
[70]	validation_0-aucpr:0.00035
[71]	validation_0-aucpr:0.00035
[72]	validation_0-aucpr:0.00035
[73]	validation_0-aucpr:0.00036
[74]	validation_0-aucpr:0.00036
[75]	validation_0-aucpr:0.00036
[76]	validation_0-aucpr:0.00035
[77]	validation_0-aucpr:0.00036
[78]	validation_0-aucpr:0.00036
[79]	validation_0-aucpr:0.00036
[80]	validation_0-aucpr:0.00036
[81]	validation_0-aucpr:0.00036
[82]	validation_0-aucpr:0.00036
[83]	validation_0-aucpr:0.00036
[84]	validation_0-aucpr:0.00036
[85]	validation_0-aucpr:0.00036
[86]	validation_0-aucpr:0.00036
[87]	validation_0-aucpr:0.00036
[88]	validation_0-aucpr:0.00036
[89]	validation_0-aucpr:0.00036
[90]	validation_0-aucpr:0.00036
[91]	validation_0-aucpr:0.00035
[92]	validation_0-aucpr:0.00034
[93]	validation_0-aucpr:0.00034
[94]	validation_0-aucpr:0.00036
[95]	validation_0-aucpr:0.00036
[96]	validation_0-aucpr:0.00036
[97]	validation_0-aucpr:0.00036
[98]	validation_0-aucpr:0.00036
[99]	validation_0-aucpr:0.00036
[LightGBM] [Info] Number of positive: 45, number of negative: 112616
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000444 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112661, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825077
[LightGBM] [Info] Start training from score -7.825077
[LightGBM] [Info] Number of positive: 45, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000294 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112662, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825085
[LightGBM] [Info] Start training from score -7.825085
[LightGBM] [Info] Number of positive: 45, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000429 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112662, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825085
[LightGBM] [Info] Start training from score -7.825085
[LightGBM] [Info] Number of positive: 44, number of negative: 112617
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000554 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112661, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000391 -> initscore=-7.847558
[LightGBM] [Info] Start training from score -7.847558
[LightGBM] [Info] Number of positive: 45, number of negative: 112617
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000313 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 112662, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.000399 -> initscore=-7.825085
[LightGBM] [Info] Start training from score -7.825085

In [15]:
df_all_cv_res

                classifier num_features     auprc
0       CatBoostClassifier            1  0.045996
1       CatBoostClassifier            1  0.000575
2       CatBoostClassifier            1  0.000540
3       CatBoostClassifier            1  0.000442
4       CatBoostClassifier            1  0.000558
5            XGBClassifier            1  0.000327
6            XGBClassifier            1  0.000365
7            XGBClassifier            1  0.000519
8            XGBClassifier            1  0.000366
9            XGBClassifier            1  0.000412
10  RandomForestClassifier            1  0.000195
11  RandomForestClassifier            1  0.000195
12  RandomForestClassifier            1  0.000195
13  RandomForestClassifier            1  0.000213
14  RandomForestClassifier            1  0.000195
15    ExtraTreesClassifier            1  0.000195
16    ExtraTreesClassifier            1  0.000195
17    ExtraTreesClassifier            1  0.000195
18    ExtraTreesClassifier            1  0.000213
19    ExtraTreesClassifier            1  0.000195
20          LGBMClassifier            1  0.000298
21          LGBMClassifier            1  0.000364
22          LGBMClassifier            1  0.000409
23          LGBMClassifier            1  0.000314
24          LGBMClassifier            1  0.000369
25  DecisionTreeClassifier            1  0.000195
26  DecisionTreeClassifier            1  0.000195
27  DecisionTreeClassifier            1  0.000195
28  DecisionTreeClassifier            1  0.000213
29  DecisionTreeClassifier            1  0.000195

## References

  Hancock, J. T., Bauder, R. A., Wang, H., & Khoshgoftaar, T. M. (2023). Explainable machine learning models for Medicare fraud detection. Journal of Big Data, 10(1), 154. https://doi.org/10.1186/s40537-023-00821-5